### ISSUE TITLE
Internal server error (503) when posting comment

### ISSUE THREAD

**Issue by mitchellspryn** [eduardoboucas/staticman#106]
Hello

I am trying to integrate staticman into my jekyll page that is being served via Github pages. I have successfully added StaticManApp as a contributor. When I try to post a comment, I'm getting a 503 internal server error. 

When I send the following request in postman:

```
https://api.staticman.net/v2/entry/mitchellspryn/mitchellspryn.github.io/master
POST
{
	"fields": 
	{
		"name": "someone",
		"email": "someone@gmail.com",
		"message": "hi"
	}
}
```

I get the following response with HTTP code 503:

```
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <title>Application Error</title>
        <style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
    </head>
    <body>
        <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
    </body>
</html>
```

My staticman.yml is as follows:

```
comments:
  allowedFields: ["name", "email", "message", "hidden"]
  branch: "master"
  commitMessage: "Add Staticman data - user comment"
  filename: "{@id}"
  format: "yml"
  url: "https://mitchellspryn.github.io"
  generatedFields:
    date:
      type: date
      options
        format: "timestamp-seconds"

    moderation: "true"
    name: "mitchellspryn.github.io"

    #TODO: Mailgun for response notification
    
    path: "_data/comments/{@id}"

    requiredFields: ["name", "email", "message"]

    transforms:
      email: md5
```

Can someone help me debug?
