### ISSUE TITLE
Verified https call to be correct but still getting GITHUB_WRITING_FILE

### ISSUE THREAD

**Issue by hxiongg** [eduardoboucas/staticman#134]
I am still using the V1 version.

I did a POST to the following
https://api.staticman.net/v1/entry/Huixiong91/my-blog/master

```
fields[message]:test1
fields[name]:testname
fields[email]:test@somemail.com
```

Getting back with status code 500
`{
    "success": false,
    "errorCode": "GITHUB_WRITING_FILE"
}`

I have added staticman to collaborator and pinged it using via https://api.staticman.net/v1/connect/Huixiong91/my-blog

Somehow staticman managed to create a branch in my repo but with nothing new added.

**Comment by petzi53** [comment]
I get same problem error message as @Huixiong91 with V2. After sending the discussion message my browser changes to [https://api.staticman.net/v2/entry/petzi53/weblog2/master/comments](https://api.staticman.net/v2/entry/petzi53/weblog2/master/comments) which I believe is correct. The manual inspection of my repo at GitHub shows that there is a difference in the URL adding `tree` bevor `master`. [https://api.staticman.net/v2/entry/petzi53/weblog2/tree/master/comments](https://api.staticman.net/v2/entry/petzi53/weblog2/tree/master/comments) . But I tried it with this URL too and got another message which I always get if a wrong URL is given.

`Cannot POST /v2/entry/petzi53/weblog2/tree/master/comments``

So I believe the first URL is the correct one, but I got the same error message as @Huixiong91.

`{"success":false,"errorCode":"GITHUB_WRITING_FILE"}`

I tried it with and without moderation.

What could be the problem?

I am not using Jekill but [Hugo](http://gohugo.io/) and [Blogdown](https://bookdown.org/yihui/blogdown/).  So maybe there is some code to change which is specific for Jekill. Unfortunately, I am a newcomer to Hugo and have no idea about Jekill. So I cannot say which lines I have to change. Maybe you could give me a hint where to look?

**Comment by eduardoboucas** [comment]
@Huixiong91 I can't find a `my-blog` repo under your account in order to investigate – perhaps it's a private repo?

@petzi53 The first URL is indeed the correct one. Have you used the `/connect` endpoint to establish a connection between Staticman and your repo? Do you see `staticmanapp` as a collaborator of your repository?

**Comment by hxiongg** [comment]
@eduardoboucas 
Yes, indeed it's a private repo, do you not support that?

**Comment by eduardoboucas** [comment]
@Huixiong91 Private repos are supported, it just means I can't look at your config to find potential issues. Do you have a `staticman.yml` file? If so, can you copy its contents and paste them [here](http://www.yamllint.com/) in order to look for YAML validation errors?

**Comment by hxiongg** [comment]
@eduardoboucas Since I am still using V1. I had the following inside `_config.yml` instead.
```
staticman: 
  allowedFields: 
    - name
    - email
    - url
    - message
  branch: master
  commitMessage: "New comment."
  filename: "comment-{@timestamp}"
  format: yml
  generatedFields: 
    date: 
      options: 
        format: iso8601
      type: date
  moderation: true
  path: "/_data/comments/{options.slug}"
  requiredFields: 
    - name
    - email
    - message
  transforms: 
    email: md5
```
