### ISSUE TITLE
Staticman Sends Multiple Pull Requests.

### ISSUE THREAD

**Issue by victorfeight** [eduardoboucas/staticman#135]
Is there any particular reason why staticman would be sending multiple pull requests on POST? 

My website code: https://github.com/victorfeight/vicstech

My comments-new.html
```
<form class="js-form form" method="post" action="https://api.staticman.net/v2/entry/{{ site.repository }}/{{ site.staticman.branch }}/comments">
  <input name="options[slug]" type="hidden" value="{{ page.slug }}" />
  <div class="form__spinner mdl-spinner mdl-spinner--single-color mdl-js-spinner is-active"></div>
  <fieldset class="field-group">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <input class="mdl-textfield__input" type="text" id="commenting-form[name]" name="fields[name]"/>
      <label class="mdl-textfield__label" for="commenting-form[name]">Your name</label>
    </div>
  </fieldset>

  <fieldset class="field-group">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <input class="mdl-textfield__input" type="text" id="commenting-form[email]" name="fields[email]"/>
      <label class="mdl-textfield__label" for="commenting-form[email]">Your e-mail</label>
    </div>
  </fieldset>

  <fieldset class="field-group">
    <div class="mdl-textfield mdl-textfield--floating-label mdl-js-textfield">
      <textarea class="mdl-textfield__input" name="fields[message]" type="text" rows= "3" id="commenting-form[message]"></textarea>
      <label class="mdl-textfield__label" for="commenting-form[message]">Your comment. Markdown is allowed.</label>
    </div>
  </fieldset>

  <fieldset class="field-group">
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
      Submit
    </button>
  </fieldset>
</form>
```

My comments.js (contains the function that allows the button to send the POST)
```
(function ($) {
  var $comments = $('.js-comments');

  $('.js-form').submit(function () {
    var form = this;

    $(form).addClass('form--loading');

    $.ajax({
      type: $(this).attr('method'),
      url: $(this).attr('action'),
      data: $(this).serialize(),
      contentType: 'application/x-www-form-urlencoded',
      success: function (data) {
        showModal('Comment submitted', 'Thanks for your message. Comments will show on my blog once they have  been approved.');
        $(form).removeClass('form--loading');
      },
      error: function (err) {
        console.log(err);
        showModal('Error', 'Sorry, there was an error with the submission!');
        $(form).removeClass('form--loading');
      }
    });

    return false;
  });

  $('.js-close-modal').click(function () {
    $('body').removeClass('show-modal');
  });

  function showModal(title, message) {
    $('.js-modal-title').text(title);
    $('.js-modal-text').html(message);

    $('body').addClass('show-modal');
  }
})(jQuery);
```

comments.html
```
<div class="js-comments">

	{% assign comments = site.data.comments[page.slug] | sort %}
	
	{% for comment in comments reversed %}
		{% assign commentData = comment[1] %}

		<article class="comment mdl-card mdl-shadow--2dp">
		  <div class="mdl-card__supporting-text">
		  	<p><strong>Comment by: </strong>{{ commentData.name }}</p>
		    <div class="comment__description">
		    	{{ commentData.message | markdownify }}
		    </div>
		  </div>
		</article>
	{% endfor %}
</div>
```

comments.scss
```
.show-modal {
	overflow: hidden;
	position: relative;
}

.show-modal:before {
	position: absolute;
	content: '';
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: 999;
	background-color: rgba(255, 255, 255, 0.85);
}

.show-modal .modal {
	display: block;
}

.constrain {
	width: 100%;
	max-width: 700px;
	margin-left: auto;
	margin-right: auto;
	padding-left: 1em;
	padding-right: 1em;
	box-sizing: border-box;
}

.form {
	position: relative;
	margin-top: 1em;
}

.form--loading:before {
	content: '';
}

.form--loading .form__spinner {
	display: block;
}

.form:before {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: rgba(255, 255, 255, 0.7);
	z-index: 10;
}

.form__spinner {
	display: none;
	position: absolute;
	top: 50%;
	left: 50%;
	z-index: 11;
}

.comment {
	width: 100%;
	margin: 20px auto;
	min-height: 0;
}

.comment__description {
	margin-top: 1em;
}

.field-group {
	display: block;
}

.mdl-card__supporting-text {
	padding-top: 20px;
        p {
          font-size: 1.4em;
        }
}

.modal {
	display: none;
	position: fixed;
	width: 300px;
	top: 50%;
	left: 50%;
	margin-left: -150px;
	margin-top: -150px;
	min-height: 0;
	z-index: 9999;
}
```

My config.yml
```
name: VicsTech
paginate: 10
url: https://victorfeight.com
repository: "victorfeight/vicstech"

# Staticman comments (full configuration in staticman.yml)
staticman:
   branch: "chalk_dev"

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
blog_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the blog page
ga_analytics: UA-102659256-1 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: false # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: victorfeight
  linkedin: # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: vrfeight@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /blog/page:num/
permalink: /blog/:slug
sass:
   style: compressed
   sass_dir: _assets/stylesheets
```

My staticman.yml
```
comments:
 allowedFields: ['name', 'email', 'message']
 branch: "chalk_dev"
 commitMessage: "New comment."
 filename: "comment-{@timestamp}"
 format: "yaml"
 moderation: true
 path: "_data/comments/{options.slug}"
 requiredFields: ['name', 'message']
```

Source: Your GitHub Pages site is currently being built from the gh-pages branch.
Webhooks: https://api.staticman.net/v1/webhook (pull_request)
Default branch: chalk_dev

Set staticmanapp as collaborator and added with https://api.staticman.net/v2/connect/victorfeight/vicstech

Now, whenever a user posts a comment on my comment page, I receive TWO staticman pull requests. What could be the reason behind this strange behavior? And if it's a configuration on my end, could someone point me in the right direction?
