### ISSUE TITLE
Generate markdown file

### ISSUE THREAD

**Issue by MattGreyDesign** [eduardoboucas/staticman#141]
Is it possible to generate a markdown file from a form submission? 

I'm aware a YAML file can be created in the `_data` directory, but I would like to make a new `.md` file with frontmatter and custom fields from the submission inside a collection so it generates a page from the data.

**Comment by eduardoboucas** [comment]
Sorry for the terribly long delay. You should be able to achieve that by using:

```yaml
format: "frontmatter"
extension: "md"
transforms:
  someContentField: "frontmatterContent"
```

Where `someContentField` is the name of your field that holds the body of the Markdown file. Hope this helps.
