### ISSUE TITLE
entries have addition unset fields

### ISSUE THREAD

**Issue by hendrixjoseph** [eduardoboucas/staticman#176]
Staticman entries are having fields that are not set. For instance, with this entry on the popcorn demo site:

https://github.com/eduardoboucas/popcorn/pull/2220

It has fields "layout" and "message" which, as far as I can tell, should not be there. For instance, this older entry does not have these extra fields:

https://github.com/eduardoboucas/popcorn/pull/2196

It also seems these fields are overwriting any fields that have the same name. This entry on my site:

https://github.com/hendrixjoseph/hendrixjoseph.github.io/pull/135

Has a blank entry for "message" which should not be empty.

**Comment by rjtngit** [comment]
This is happening on my site as well. I renamed the field as a workaround in the meantime.

**Comment by MiKatre** [comment]
I noticed the same thing on my site as well, although it is not causing any issues. And the field "layout" is set to "post" which is what I need.

**Comment by IanCaio** [comment]
Just made a quick test and it's confirmed here too:

[iancaio/staticmanapptest#7](https://github.com/IanCaio/staticmanapptest/pull/7)

**Comment by IanCaio** [comment]
I made another test and the `layout`, `timestamp` and `message` fields are gone, but now there's a new unset field being added: `approved: false`. That's very odd, I wonder if the instance of `staticman` running on the website is the same as the one here on Github, because I've been hunting the source code for leads and haven't found anything so far.. Maybe @eduardoboucas is testing some new features?

[iancaio/staticmanapptest#8](https://github.com/IanCaio/staticmanapptest/pull/8)

**Comment by mmistakes** [comment]
Noticing the same thing across a couple repos. 

Not exactly sure how to reproduce it as it doesn't always happen. The only common pattern I've noticed is `message: ' '` will be blanked out when these extra fields start showing up (in my case `approved`, `title`, and `layout`.) 

Example:

```yaml
_id: 41f07470-17bf-11e8-b61b-7b344215416b
message: ' '
url: ''
approved: false
title: Comment
layout: post
```

https://github.com/mmistakes/made-mistakes-jekyll/pull/590/commits/25eef0999623a5bf42fae57a97ee566e0050c130

https://github.com/mmistakes/minimal-mistakes/pull/1543/commits/48c1dfb7cc6b365e8c13609c920fee3e8d745944

https://github.com/Xabacadabra/Xabacadabra.github.io/commit/cc0306205c6800b3837c7e3e278e5b332f3e7349

**Comment by eduardoboucas** [comment]
This is bizarre. I’m not testing any new feature (and wouldn’t do so on the live API anyway). I’ll try to look into this in the next couple of days.

**Comment by eduardoboucas** [comment]
Trying to find a pattern common to people having this issue. Do you have moderation enabled or disabled? Are you all using Jekyll?

`layout: post` sounds like something Jekyll would use, but why would that be sent to Staticman? It's really confusing!

**Comment by MiKatre** [comment]
This happened to me using Hexo with moderation enabled. However, the issue disappeared a week ago when i added new fields.

**Comment by mmistakes** [comment]
Jekyll and moderation on both sites. The strange thing is one doesn’t have a `post` layout yet somehow it’s being assigned.

**Comment by hendrixjoseph** [comment]
shouldn't the "allowedFields" parameters cause staticman to deny any extra fields submitted?

**Comment by hendrixjoseph** [comment]
I'm trying to capture the actual post request and response in my browser's developer tools, but of course I can't even duplicate the bug right now.

**Comment by hendrixjoseph** [comment]
details for me: GitHub pages (Jekyll), StaticMan V2, moderation enabled

**Comment by IanCaio** [comment]
Details: GitHub Pages (Jekyll), Staticman V2, Moderation enabled.

Right now I can't replicate the bug. The last time I could was [2 days ago](https://github.com/IanCaio/staticmanapptest/pull/11), where the `approved` and `title` fields were still being added.

**Comment by JokerQyou** [comment]
I'm using Hugo with Staticman V2, moderation enabled. Observed additional fields varies from entry to entry. But all the entries were created by spam bots this year. Some of the fields are `commentDate`, `tags` and `layout`.
Although with moderation enabled, these entries will not be published to my site directly, but it is possible for spam bots to blow up Github pull requests.

**Comment by eduardoboucas** [comment]
Sorry for the slow response from my part on this issue. This is a really difficult issue to replicate.

First of all, has anyone seen an instance of this where the submission was not sent by a spam bot? This is important to understand whether Staticman is simply processing the fields it receives, or whether it's somehow injecting random fields on its own (I think the latter is very unlikely).

Also, can each of you confirm whether you're using `allowedFields` property in your Staticman configs? As @hendrixjoseph rightly pointed out, this should block entries with fields that are not in that whitelist. I did find an issue with this, which made it so that if a field that was not in `allowedFields` was sent in the payload _and_ its contents were empty, it did go through as an empty string. This has been fixed.

This doesn't explain, however, reports of extra fields being added with content (e.g. `layout: "post"`). The only explanation that fits my current theory is that spam bots are sending this _and_ site owners do not have an `allowedFields` property.

**Comment by JokerQyou** [comment]
Yes I am, in `staticman.yml`: `allowedFields: ["name", "email", "url", "content", "reply_to"]`. With this config I'm still getting extra fields like I previously said.

Actually, the first example given by @hendrixjoseph is what you are looking for: the popcorn site has `allowedFields` set, and it was receiving pull requests with extra fields. Also, I don't think that one was submitted by a spam bot. https://github.com/eduardoboucas/popcorn/pull/2220

**Comment by eduardoboucas** [comment]
> With this config I'm still getting extra fields like I previously said.

Are you able to replicate this yourself?

**Comment by JokerQyou** [comment]
No, I cannot. All the pull requests in my repo with this problem were submitted by spam bots.

**Comment by eduardoboucas** [comment]
I really don't understand how they are coming through. 😞

**Comment by eduardoboucas** [comment]
I have added some logging at request level for debugging, so I'll keep an eye on it in the next few days to see what's up.

**Comment by JokerQyou** [comment]
So another new comment went through 3 hours ago, I wonder if you caught it in log. The file content is as follows:

```yaml
_id: e7b19280-2b5c-11e8-86f2-611b1a84ae15
content: "I Ԁdo know!? Sɑid Larry. ?I wager he likes angｅⅼs aas a reѕult of hhe has \r\ntheem around all of the time. Possibly he and thе \r\nangels play houseһold gaеs like we do sometіmes. Possibly they play \r\nMonopoly.? This mwde Mommy chortle really hard."
name: example.net
email: 29218ddb8706250663d6999551c2c519
url: 'http://example.net/'
date: 1521453866
layout: post
```

Notice: I've replaced the website URL and user name with an example domain, other characters remain unchanged.

**Comment by eduardoboucas** [comment]
@JokerQyou Can you show me the contents of your `staticman.yml`? This is really strange. I did catch it in the log and there's no mention of `date` or `layout` fields anywhere in the request, so Staticman is inserting them on its own somehow!

**Comment by mmistakes** [comment]
I made a [test comment](https://github.com/eduardoboucas/popcorn/pull/2463/files) to the Popcorn demo site earlier today, and noticed it was leaking `layout` into the datafile.

**Comment by eduardoboucas** [comment]
This is super useful information, thank you both. I'll keep working on tracking it down.

**Comment by JokerQyou** [comment]
`date` is one of `generatedFields`, so that field is natural. Here is my config file (`staticman.yml`):

```yaml
comments:
  allowedFields: ["name", "email", "url", "content", "reply_to"]
  allowedOrigins: ["example.net"]
  branch: "master"

  commitMessage: "Staticman: new comment posted"

  filename: "comment-{@timestamp}"

  format: "yml"
  extension: "yaml"

  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"

  moderation: true

  name: "XXX"

  path: "data/comments/{options.entryId}"

  requiredFields: ["name", "email", "content"]

  transforms:
    email: md5

```

**Comment by IanCaio** [comment]
For a while the problem seemed to vanish, but seeing the updates here I tested once again and the extra fields are being injected. No spam bots, just submitting manually from [this page](https://iancaio.github.io/staticmanapptest/).

_staticman.yml_:

```yml
test:
  allowedFields: ["name", "age"]
  branch: "master"
  filename: "{@id}"
  format: "json"
  moderation: true
  path: "_data/test"
  requiredFields: ["name", "age"]
```

Last pull request from Staticman:

https://github.com/IanCaio/staticmanapptest/pull/16

**Comment by dancwilliams** [comment]
I am seeing this issue as well.

My site code is public so you can check it out here: https://github.com/dancwilliams/networkhobo

It looks like extra fields started showing up in April 14.  Before that everything looks clean.  I really didn't notice until today because a lot more seems to be added now.

Comment before April 14:

```yaml
_id: a8326030-2dbe-11e8-a67d-bb93e6150b56
_parent: 2014-07-22-godaddy-delegate-subdomain-to-different-nameserver
reply_to: 48365630-2d34-11e8-9f0c-3b52df5f76db
name: Dan
email: 9162d0c5aca33e7e4c8ec6fc3d44f541
body: "Maurizio,\r\n\r\nI wish I could help, but I migrated away from using GoDaddy a few years ago so I have no way to test. I hope that maybe someone on here will be able to help. I do hope you are able to get this working!\r\n\r\nDan"
date: '2018-03-22T10:49:12.829Z'
```

Comment today:

```yaml
_id: f41abd80-524e-11e8-be5f-67f0db2d8ce5
_parent: >-
  2013-12-23-cisco-unified-communications-manager-unity-connection-sftp-emergency-backup-to-mac-os-x-over-the-internet
reply_to: cfdb8280-f932-11e7-89d4-e59a38d801c6
name: Dan
email: 65d26dd351e6902fa5ca05019085394a
body: Test again
date: '2018-05-07T23:32:49.554Z'
tags:
  - comment-subscription
layout: verslag
message: ' '
visible: true
excerpt_separator: <!--more-->
draft: true
```

The only changes I have made is updating my version of Hugo so I rolled Hugo back to 0.36 just to test and I received the same behavior.  You can see this in my recent commit history.

I am also noticing that e-mail notifications are not going out and that new addresses are not being added to lists in mailgun.

This is the post where I test commenting.  Feel free to make some test comments and see output:  https://networkhobo.com/2013/12/23/cisco-unified-communications-manager-unity-connection-sftp-emergency-backup-to-mac-os-x-over-the-internet/

Also, if you look at the recent closed PRs, you will see a lot of garbage in them: https://github.com/dancwilliams/networkhobo/pull/205

Let me know if there is any way I can help.
