### ISSUE TITLE
Cannot get staticman to display comments in posts

### ISSUE THREAD

**Issue by fpgits** [eduardoboucas/staticman#282]
I have followed several tutorials to implement comments via staticman for my personal site but I have not been able to show the comments in the publications, the only thing that is shown is the comment counter.

You can see what is mentioned in the following sample post:
https://www.fernandoportela.net/blog/plataforma-venezuela-giro180

--
https://github.com/fernandoportelab/blogpersonal
https://github.com/fernandoportelab/blogpersonal/tree/master/_includes
--

Thank you very much for your cooperation in advance.

**Comment by hawkeye116477** [comment]
Maybe try changing URL here `https://github.com/fernandoportelab/blogpersonal/blob/master/_includes/new-comments.html#L5`, just remove `_data` from it.

**Comment by fpgits** [comment]
Hey @hawkeye116477 , thanks for your attention.

I have done what you say but they still do not appear, simply the counter is shown in the posts but not the content of the comment.

**Comment by VincentTam** [comment]
@fernandoportelab This repo is about the Node.JS app that collects user input from an HTML `<form>` and converts it into YML files in your repo.  As https://github.com/fernandoportelab/blogpersonal/commit/3794679242f4b28ce6225b7ba0eefd22ff2280a6 shows, this Node.JS app has done its job, so it remains a Jekyll problem to convert YML files like

```yaml
_id: d1f0c950-6307-11e9-a5be-138718db59ab
name: test
email: 319f7c45e3cb26186e0a66328dca8b90
url: ''
message: wqewqewqewqewqewqewqewqewqewqewqewqewqewqewqewqewqewqewqewqe
date: '2019-04-20T01:01:26.565Z'
```

into an HTML element representing a comment.  I invite you to refer to [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) for a working Staticman integration template code written in Jekyll, and reframe this as a pure Jekyll question on  [Jekyll Talk](https://talk.jekyllrb.com/).

Reference: https://github.com/eduardoboucas/staticman/issues/264#issuecomment-460446511
