### ISSUE TITLE
500 error "INVALID_VERSION"

### ISSUE THREAD

**Issue by rskupnik** [eduardoboucas/staticman#287]
POSTing to this: `https://api.staticman.net/v3/entry/github/rskupnik/rskupnik.github.io/master/comments`

With the following data:
```
options[slug] | hello-world
fields[name] | Myz
fields[email] | myzek92@gmail.com
fields[message] | Hello+comments
```

Config:
```
comments:
    allowedFields: ["name", "email", "message"]
    filename: "{@id}"
    branch: "master"
    path: "_data/comments/{options.postId}"
    filename: "{@id}"
```

I'm receiving a 500 error with the following json: `{"success":false,"errorCode":"INVALID_VERSION"}`
