### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by thierrybgentile** [eduardoboucas/staticman#30]
First I want to say this project is amazing and thank you for it. One of the first things that came to mind when I heard about it is the possibility to make an open publishing kind of blog/platform out of it. In fact I'm doing that right now. I want to point the path in a Jekyll blog to _posts/ and see if i can make this work such that the form generates markdown files with a few markdown fiels at the top. I guess to make that work ideally we'd need support for markdown as well, not just YAML and JSON, right? 
How easy would that be to build in? I'm interested in contributing though I'm mostly a begginner javascript dev.

**Comment by eduardoboucas** [comment]
Thanks! I'm glad you find it useful.

That's a very interesting idea. What you need is effectively a way of outputting a Markdown file with the front-matter format used by Jekyll to create a post (which is effectively Markdown), as well as the post body.

The first option that comes to mind is to add a new output format (called `post` perhaps), as well as a new transform type (called `post-body`).

_Form example:_

``` html
<input type="hidden" name="fields[category]" value="music">
<input type="text" name="fields[title]">
<textarea name="fields[body]"></textarea>
```

_Staticman config:_

``` yaml
format: 'post'
transforms:
  body: 'post-body' # This will tell Staticman that this field is the post body
```

_Output:_

``` yaml
category: "music"
title: "Whatever is typed into title"
---
Whatever is typed into the post body. It can have Markdown or HTML, Staticman doesn't care
```

Does that make sense?

**Comment by thierrybgentile** [comment]
Yes it does make sense. That would be really great.

**Comment by eduardoboucas** [comment]
I'm think it would be useful to spin up a test instance of the Staticman API (on a free Heroku instance) to test new features. Would you be able to assist with test driving this once I implement?

**Comment by thierrybgentile** [comment]
I'll do my best! I don't know much about testing but I'll look it up and test as much stuff as I can with my little prototype.

**Comment by eduardoboucas** [comment]
I was finally able to look at this (sorry I took ages). I've pushed this feature to a new test instance. Here's how you can use it:
1. Add the following to your config, where `yourContentField` is the name of the field you want to use as the post body
   
   ``` yaml
   format: "frontmatter"
   transforms:
     yourContentField: "frontmatterContent"
   ```
2. Change your Staticman URL from `https://api.staticman.net` to `https://dev.staticman.net`.

It's a test instance, so it might be a bit slow. Can you give it a test, see if it does what you're after and let me know of any issues?

Thanks!
