### ISSUE TITLE
Multiple instances on the Same Site

### ISSUE THREAD

**Issue by vwchu** [eduardoboucas/staticman#32]
# Enhancement

Currently there is support for only one instance of Staticman per static site since the staticman property is a hash in the configuration file. For instance `_config.yml`:

``` yaml
staticman:
  name          : "comments"
  allowedFields : ['name', 'email', 'url', 'message']
  branch        : "master"
  commitMessage : "New comment."
  filename      : comment-{@timestamp}
  format        : "yml"
  moderation    : true
  path          : "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email       : "md5"
```

I am wondering if more than one configuration could be specified if the `staticman` property could be an array. Each hash in the array, requires an additional property `name`, and in the submitted form, we must pass an additional required field `options[name]` with the corresponding `name` value so that the server can know which instance to use. This would be backward compatibility, since if the `staticman` property is a hash, it behaves like it does in the current version, and if it is an array, it enables this new behaviour. For example:

``` yaml
staticman:

  - name          : "ideas"
    allowedFields : ['title', 'description']
    branch        : "master"
    commitMessage : "New idea."
    filename      : idea-{@timestamp}
    format        : "yml"
    moderation    : true
    path          : "_data/ideas/{options.slug}"
    requiredFields: ['title', 'description']

  - name          : "comments"
    allowedFields : ['name', 'email', 'url', 'message']
    branch        : "master"
    commitMessage : "New comment."
    filename      : comment-{@timestamp}
    format        : "yml"
    moderation    : true
    path          : "_data/comments/{options.slug}"
    requiredFields: ['name', 'email', 'message']
    transforms:
      email       : "md5"
```

``` html
<form method="POST" action="https://api.staticman.net/v1/entry/my/repo/master">
  <input name="options[name]" type="hidden" value="ideas">
  <input name="options[slug]" type="hidden" value="{{ page.slug }}">
  <label><input name="fields[title]" type="text">Title</label>
  <label><textarea name="fields[description]"></textarea>Description</label>
  <button type="submit">Submit Idea!</button>
</form>

<form method="POST" action="https://api.staticman.net/v1/entry/my/repo/master">
  <input name="options[name]" type="hidden" value="comments">
  <input name="options[slug]" type="hidden" value="{{ page.slug }}">
  <label><input name="fields[name]" type="text">Name</label>
  <label><input name="fields[email]" type="email">E-mail</label>
  <label><textarea name="fields[message]"></textarea>Message</label>
  <button type="submit">Submit Comment!</button>
</form>
```

**Comment by eduardoboucas** [comment]
I like this!

I think I would prefer to add this for version 2 of the endpoint (see #5 for more details). Sharing the configuration file with Jekyll was a design mistake, and "polluting" it to yet more Staticman-related stuff doesn't seem ideal.

With version 2, we have a dedicated configuration file for Staticman, and in that case yes, absolutely. Maybe each instance could be a property within the main object and get rid of `name`, so something like:

``` yaml
ideas:
  - allowedFields : ['title', 'description']
    branch        : "master"
    commitMessage : "New idea."
    filename      : idea-{@timestamp}
    format        : "yml"
    moderation    : true
    path          : "_data/ideas/{options.slug}"
    requiredFields: ['title', 'description']

comments:
  - allowedFields : ['name', 'email', 'url', 'message']
    branch        : "master"
    commitMessage : "New comment."
    filename      : comment-{@timestamp}
    format        : "yml"
    moderation    : true
    path          : "_data/comments/{options.slug}"
    requiredFields: ['name', 'email', 'message']
    transforms:
      email       : "md5"
```

Does that sound reasonable?

Thanks for creating the issue.

**Comment by eduardoboucas** [comment]
Also, I'm thinking the name of the instance should be provided as part of the URL instead of relying on a form field, being such a crucial setting.

So something like:

```
https://api.staticman.net/v2/entry/{your GitHub repository}/{your repository name}/{the name of the branch}/{the name of the instance}
```

With the name of the instance being optional.

**Comment by vwchu** [comment]
@eduardoboucas I think you meant this (instead of the nested arrays; probably a typo):

``` yaml
ideas:
  allowedFields : ['title', 'description']
  branch        : "master"
  commitMessage : "New idea."
  filename      : idea-{@timestamp}
  format        : "yml"
  moderation    : true
  path          : "_data/ideas/{options.slug}"
  requiredFields: ['title', 'description']

comments:
  allowedFields : ['name', 'email', 'url', 'message']
  branch        : "master"
  commitMessage : "New comment."
  filename      : comment-{@timestamp}
  format        : "yml"
  moderation    : true
  path          : "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email       : "md5"
```

-- for the record
