### ISSUE TITLE
Can't comment despite all the setup

### ISSUE THREAD

**Issue by shreyasbapat** [eduardoboucas/staticman#356]
I am getting : "Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again." on clicking submit button. I am unable to localise the issue to what the problem can be: 

https://blog.einsteinpy.org/2020-05-18-GSoC-20-Brief-History/ This is the blog post.

This is the repository for enabling the comments: https://github.com/einsteinpy/blog.einsteinpy.org

Any leads will be appreciated.

**Comment by iootaa** [comment]
You should try to remove reCaptcha just the time to make the test

**Comment by shreyasbapat** [comment]
> You should try to remove reCaptcha just the time to make the test

I am sorry, I did not quite understand what you meant

**Comment by alexwaibel** [comment]
> > You should try to remove reCaptcha just the time to make the test
> 
> I am sorry, I did not quite understand what you meant

It means you should try disabling reCaptcha in your `staticman.yml` temporarily to see if that resolves the issues you're facing.

```yaml
# reCAPTCHA (OPTIONAL)
# Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
# Use your OWN siteKey and secret.
reCaptcha:
  enabled: false
```
