### ISSUE TITLE
Akismet documentation

### ISSUE THREAD

**Issue by datapolitical** [eduardoboucas/staticman#414]
I've tried setting up akismet but even the "verified spam" submissions from their API keep getting through, so obviously it's not actually working.

I wish there was just a simple writeup with actual examples because the issues on here have conflicting information about how the akismet account should be set up (whether the site URL should be your Staticman instance or your website).

It feels like a lot of people want to use this, and it works, but no one who knows how to get it working has really taken the time to document exactly, step by step, how to do so with examples. Even the blogs about Staticman don't have much about it. 

If something is a real feature the docs should be good enough that people can follow it easily and get it working, otherwise you're just asking for people to be frustrated.

**Comment by datapolitical** [comment]
Solved it. You need to set all the akismet variables in the docs for site config.

but now main.js isn’t handling a spam error properly.

**Comment by RyanTG** [comment]
Yeah, I'm either misunderstanding the docs or the docs aren't telling the full story.

https://staticman.net/docs/spam says to simply add the `AKISMET_API_KEY` and `AKISMET_SITE` into the staticman config variables (in heroku, in my case). And that's it.

But that's not working for me. Can you state more clearly what you also did? Did you add things to your jekyll config.yml and/or staticman.yml files (if you're using jekyll)?

I just looked up one of your repos, and saw that you have this in staticman.yml:

````
# Akismet spam detection
          akismet:
            enabled: true
            author: "name"
            authorEmail: "email"
            authorUrl: "url"
            content: "message"
````

Is that what fixed it? That is not in the official staticman sample yml, nor in the docs, so I wouldn't have known to do that.
