### ISSUE TITLE
Email notification upon replies

### ISSUE THREAD

**Issue by TWiStErRob** [eduardoboucas/staticman#42]
Usually commenting solutions allow for users to be notified via email about replies to their comments, or in case of a flat commenting stream when anyone posts a new comment. Is it possible to do this with staticman?

**Comment by eduardoboucas** [comment]
This is currently in development and will be released soon!

**Comment by illus0r** [comment]
@eduardoboucas looking forward to it! I've just discovered, I've received a first comment on my blog. This comment is useful, but I'm not able to say “Thank you” to it's author.

**Comment by eduardoboucas** [comment]
The feature is pretty much ready. I could use with some help with testing. Would any of you be interested in being the guinea pig? 😄

**Comment by illus0r** [comment]
@eduardoboucas ready!

**Comment by eduardoboucas** [comment]
Okay, here's how to get notifications working.

Emails are sent using [Mailgun](http://www.mailgun.com/). There is an account associated with the public instance of Staticman, but it comes with a limit of 10,000 emails a month. This limit shouldn't be an issue in the immediate future, but users are encouraged to use their own Mailgun accounts instead. They are free (for the first 10k emails), but you do need a custom domain to use them with. I can possibly provide *.staticman.net subdomains.

To enable notifications, you need a `notifications` block in your site config and you must be using the config file format introduced in `v2` (i.e. having a `staticman.yml` file, instead of using Jekyll's `_config.yml`). See the [sample config file](https://github.com/eduardoboucas/staticman/blob/master/staticman.sample.yml) for more info.

If you're using your own Mailgun account, you'll need to add a Mailgun API key and domain to the config, which need to be encrypted. To encrypt those, you can use the following endpoint: `https://api.staticman.net/v2/encrypt/{TEXT TO BE ENCRYPTED}`.

Next, your entries will need to specify that a user wishes to subscribe to a specific entry. This is an example:

 ```html
<form method="POST" action="https://api.staticman.net/v2/entry/joebloggs/my-site/master/comments">
  <input type="hidden" name="options[origin]" value="http://mysite.com/post1.html">
  <input type="hidden" name="options[parent]" value="867bd1e0-921c-11e6-930f-79eeedf443ea">
  
  <input type="text" name="fields[name]" placeholder="Title">
  <input type="text" name="fields[email]" placeholder="Email">
  <textarea name="fields[body]"></textarea>
  <input type="checkbox" name="options[subscribe]" value="email">
  
  <button type="submit">Go!</button>
</form>
```

In the from above, you can see the following:

- `options[origin]` contains the full URL of the entry. This will be included in the email sent to subscribers, allowing them to open the post directly.
- `options[parent]` is a unique identifier to the entry the user is subscribing to. This could be the title of a post (although it needs to be URL-friendly, so this needs to be a slug) or the `_id` field (which is now automatically added to every entry) if you want to subscribe to another comment.
- `options[subscribe]` contains the name of the field corresponding to the email address of the subscriber.

Finally, and to make sure we don't send emails asking users to click on links that have been spoofed, you need to add an `allowedOrigins` field ([see docs](https://staticman.net/docs/configuration#allowedOrigins)) to your site config, where you'll specify which domains are valid origins. If you add only `mysite.com`, then an entry where `options[origin]` is `http://myothersite.com/post1.html` will be rejected.

I'm sure there are still a few rough edges, so if any of you can try implementing this and share your feedback that'd be very useful.

Thanks!

**Comment by dancwilliams** [comment]
Works great!  Thanks for your work on this!

**Comment by zongren** [comment]
Is this working on public staticman instance?
I tried it a couple of times and failed.
Here is my staticman.yml:

```
allowedFields: ["name", "email", "url", "message", "origin", "parent", "subscribe"]
requiredFields: ["name", "message"]
format: "json"
generatedFields:
  date:
    type: "date"
    options:
      format: "iso8601"
moderation: true
branch: "master"
path: _data/{options.slug}
filename: comment-{@timestamp}
transforms:
  email: md5
name: "宗仁的博客"
allowedOrigins: ["localhost", "zongren.me"]
notifications: 
  enabled: true
  apiKey: "qPB1uWby7FS6T0wgLqUfjcQkkVtLkcergXOqiEoZyTo5yqMmGU/cuzOD825KOZkvbE7m0mOYo2LKPj82v+BcQDxxcIULev8lwpQ1KZJwjv6Ei3f1HbFyIq5N2Ehmya3PyPGga3IaedFVTPFrue67DQ2W5+tu8xJX1S2PahUEgAA="
  domain: "FkFQQFNFX96xVIOYvgtB8IxeBP60lZa/sUhHv0Y3KWV3EdRjMLED0zZr6nGGC5opytzczKvQtR2Y6YJvKQ2ltOBV1aFuAvsN/HPnOZ4e5JMBI+BjGWWlaqUsKp/mNGq/q9oWDk3FT8tdfw7UBqa8lC99eYa+QMXj/k+gpPx5ki0="
```
and comment form:
```
<form class="comment-form" method="POST" action="https://api.staticman.net/v2/entry/<%- theme.staticman %>">
    <input type="hidden" name="options[origin]" value="<%- config.url %><%- config.root %><%- item.path %>">
    <input type="hidden" name="options[parent]" value="<%- item.slug %>">
    <input type="hidden" name="options[redirect]" value="<%- config.url %><%- config.root %><%- item.path %>">
    <input type="hidden" name="options[slug]" value="<%- item.slug %>">
    <span class="comment-form__input-wrapper">
      <input autocomplete="off" spellcheck="false" class="comment-form__input" name="fields[name]" type="text" placeholder="请输入姓名"/>
    </span>
    <span class="comment-form__input-wrapper">
      <input autocomplete="off" spellcheck="false" class="comment-form__input" name="fields[email]" type="email" placeholder="请输入邮箱（可选）"/>
    </span>
    <span class="comment-form__input-wrapper">
      <input autocomplete="off" spellcheck="false" class="comment-form__input" name="fields[url]" type="url" placeholder="请输入你的网站（可选）"/>
    </span>
    <span class="comment-form__input-wrapper">
    <textarea class="comment-form__input comment-form__input--textarea" name="fields[message]" placeholder="请输入评论内容（支持Markdown）"></textarea>
    </span>
    <input type="checkbox" name="options[subscribe]" value="email" id="subscribe" /><label for="subscribe">订阅此文章的评论</label>
    <button class="comment-form__input comment-form__input--button">提交评论</button>
  </form>
```
And there are no logs on my mailgun dashboard.
