### ISSUE TITLE
Limited number of fields?

### ISSUE THREAD

**Issue by taxilly** [eduardoboucas/staticman#47]
Hey, I was wondering if there was a limit on the number of fields that we can use? Since I always keep getting; for example:

`[{"code":"INVALID_FIELDS","data":["contact","link"]}]`

When I use ~7 or more fields, my POST form is setup like this:

```
	<form method="POST" action="https://api.staticman.net/v1/entry/twentytwoo/{{ site.github.repo }}/gh-pages">
	  <input name="options[redirect]" type="hidden" value="{{post.url}}">
	  <input name="options[slug]" type="hidden" value="{{page.slug}}">
	  <input class="col-md-2 col-xs-12" name="fields[title]" type="text" placeholder="Startpage title">
	  <input class="col-md-2 col-xs-12" name="fields[author]" type="text" placeholder="Author">
	  <input class="col-md-2 col-xs-12" name="fields[contact]" type="text" placeholder="Contact (optional)">
	  <input class="col-md-6 col-xs-12" name="fields[description]" type="text" placeholder="Short description of your startpage.">
	  <input class="col-md-6 col-xs-12" name="fields[image]" type="text" placeholder="Screenshot image URL">
	  <input class="col-md-6 col-xs-12" name="fields[link]" type="text" placeholder="Link to your site (optional)">
	  <textarea class="col-md-12 col-xs-12" name="fields[source]" placeholder="Your startpage code here."></textarea>
	  <button class="col-md-1 col-xs-12" type="submit" style="margin-bottom: 2px;">Submit</button>
	</form>
```

And a snippet of my _config.yml:

```
# Staticman
staticman:
  allowedFields: ['title','author','contact','description','image','link','source']
  branch: 'gh-pages'
  commitMessage: "New startpage submission."
  filename: submission-{@timestamp}
  format: 'yaml'
  moderation: true
  path: "submissions/_posts/{options.slug}"
  requiredFields: ['title','author','description','image','source']
```
