### ISSUE TITLE
Ignore trailing slash from path field

### ISSUE THREAD

**Issue by Ilphrin** [eduardoboucas/staticman#68]
Hi!

First, thank you for your awesome tool ;) Since a few weeks I have a trouble creating comments on my blog, Staticman creates a branch on my repository, but doesn't create a commit, and when submitting a new comment I have this page:

```json
{

  "code": 422,

  "status": "Unprocessable Entity",

  "message": "{\"message\":\"path contains a malformed path component\",\"errors\":[{\"resource\":\"Commit\",\"field\":\"path\",\"code\":\"invalid\"}],\"documentation_url\":\"https://developer.github.com/v3/repos/contents/\"}"

}
```

Here is my staticman.yml:
```yml
comments:
  path: "_data/comments/"
  allowedFields: ["name", "email", "url", "message", "post_id"]
  allowedOrigins: ["ilphrin.com", "localhost"]
  branch: "master"
  filename: "{fields.name}_{@timestamp}"
  format: "yml"
  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"
  moderation: true
  name: "ilphrin.com"
  requiredFields: ["name", "email", "message", "post_id"]
  commitMessage: "New comment on the blog"

```
And here is my form for submitting a comment (I am using Jekyll):

```html
  <form class="ui form" method="POST" action="https://api.staticman.net/v2/entry/Ilphrin/ilphrin.com/master/comments">
    <input name="options[slug]" type="hidden" value="{{ page.slug }}">
    <input name="options[redirect]" type="hidden" value="https://ilphrin.com{{page.url}}">
    <input name="options[origin]" type="hidden" value="https://ilphrin.com" />
    <input type="hidden" name="fields[post_id]" value="{{page.id}}" />
    <div class="ui inverted segment">
      <h2 class="ui dividing header">Commenter</h2>
      <div class="field">
        <div class="three fields">
          <div class="field">
            <label>Nom</label>
            <input name="fields[name]" placeholder="Requis" type="text" required/>
          </div>
          <div class="field">
            <label>Email</label>
            <input name="fields[email]" placeholder="Requis, non publié" type="email" required/>
          </div>
          <div class="field">
            <label>Lien</label>
            <input name="fields[url]" placeholder="Optionnel" type="text"/>
          </div>
        </div>
      </div>
      <div class="field">
        <label>Allez-y parlez ;)</label>
        <textarea name="fields[message]" placeholder="Requis" required></textarea>
      </div>
      <button class="ui submit button" type="submit" name="submit">Envoyer</button>
    </div>
  </form>
```

And I couldn't figure out how to fix this issue :/
