### ISSUE TITLE
Endpoints for repos within organization

### ISSUE THREAD

**Issue by kishaningithub** [eduardoboucas/staticman#69]
My repo is there at
https://github.com/mantrayatra/mantrayatra.com

What must be the POST endpoint? (Note my user name kishaningithub is NOT there in the github repo URL since its tied to an organisation)
For authentication the following worked :-)
https://api.staticman.net/v2/connect/mantrayatra/mantrayatra.com

But for form submission i am unable to decipher the URL
I tried all these but no luck :-(
https://api.staticman.net/v2/entry/mantrayatra/mantrayatra.com/master/
https://api.staticman.net/v2/entry/kishaningithub/mantrayatra/mantrayatra.com/master/
https://api.staticman.net/v2/entry/kishaningithub/mantrayatra.com/master/

So what is the form POST URL ?

**Comment by eduardoboucas** [comment]
It should be https://api.staticman.net/v2/entry/mantrayatra/mantrayatra.com/master (without the trailing slash). Could you try that?

**Comment by eduardoboucas** [comment]
Actually, you're missing the property name in the URL if you're using a `v2` endpoint (e.g. https://api.staticman.net/v2/entry/mantrayatra/mantrayatra.com/master/comments). I don't see any Staticman config file in your repository though. Can you post a link to it?

**Comment by kishaningithub** [comment]
Thanks for the blazing fast response!! :-)

Tried hitting  
https://api.staticman.net/v2/entry/mantrayatra/mantrayatra.com/master/reviews
(Note its `reviews` instead of `comments`)
and the request fails.

My staticman.yml
```yaml
reviews:
  allowedFields: ["name", "email", "stars", "review"]
  allowedOrigins: ["localhost", "mantrayatra.com"]
  branch: "master"
  filename: "{@id}"
  format: "yaml"
  generatedFields:
    date:
      type: date
  moderation: true
  path: "data/reviews/{options.entryId}"
  requiredFields: ["name", "email", "stars", "review"]
  transforms:
    email: md5
```

I am just setting up static man for my site. So the change is in local

Should i push and check ?
