### ISSUE TITLE
Support counters on posts

### ISSUE THREAD

**Issue by vwchu** [eduardoboucas/staticman#73]
It might useful to add the ability for users to increment or decrement a set of specified counter fields for a specific comment or post. For instances:

```yaml
comments:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "master"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  counters:
  - name: "vote"
    field: "votes"
    operation: "increment"
```

Then, every time the endpoint `https://api.staticman.net/v2/entry/user/project/master/comments/{id}/vote` is called it updates the value of the `votes` property in the file for the comment, as oppose to creating an entirely new file.

Before:

```yaml
name: 'Bob Smith'
email: '...'
message: '...'
votes: 0
```

After:

```yaml
name: 'Bob Smith'
email: '...'
message: '...'
votes: 1
```

**Comment by eduardoboucas** [comment]
This is an interesting idea, but perhaps a bit too ambitious, as it pretty much transforms the repository into a flat file database. The current version *sort of* is that already, but I anticipate complexities with the introduction of the ability to update a file rather than creating a new one every time.

For example, imagine the initial state as:

```yaml
name: 'Bob Smith'
email: '...'
message: '...'
votes: 0
```

Then someone submits an entry, so we read the file and look at the value of `votes`. We see that it's `0`, so we create a PR to change that to `1`. In the meantime, and before PR 1 has been accepted, there's another entry. We go through the same process, but the value at that point is still `0`, so PR 2 will also try to set the value to `1` (and not `2`), because it's not aware of PR 1 (which may or may not be accepted).

Does that make sense?
