### ISSUE TITLE
frontmatterContent field is not working on production server

### ISSUE THREAD

**Issue by ctrl-b** [eduardoboucas/staticman#91]
Using the next options in api.staticman.com doesn't work as expected

```
format: frontmatter
transforms:
  mdfield: "frontmatterContent"

```
It generates a field where the mdfield is included in the yaml block instead of the content area of the markdown file.

Additional random behaviors:

Extra fields added:

```
layout: verslag
excerpt_separator: <!--more-->
```

If the field is optional and not filled out the content area of the markdown file is generated as undefined

In **dev.staticman.com**

Only when the field is empty it generates undefined in the content area, the other option works correctly

**Comment by eduardoboucas** [comment]
There is no `mdfield` property, it's `contentField`. Could you try with that?

**Comment by ctrl-b** [comment]
Hi @eduardoboucas ,

Correct me if I'm doing something wrong,

In the `allowedFields:` property I added `content`

`allowedFields: ["title", "content", "name", "email", "twitter"]`

Then in `format` I use the value `frontmatter` to generate a markdown file

Finally, in `transforms` I took the field added in `allowedFields` and add the value `"frontmatterContent"` so, that field Is going to be used as the body of the post/file 

the result something like:



```
allowedFields: ["title", "content", "name", "email", "twitter"]
format: frontmatter
transforms:
  email: md5
  content: frontmatterContent
```


Is that correct? or where do the contentField needs to be used?


thanks!

**Comment by eduardoboucas** [comment]
Sorry, @usrix. My previous comment made absolutely no sense.

That looks correct. Are you getting any errors at all?

I'll test this myself over the weekend.

**Comment by ctrl-b** [comment]
@eduardoboucas 

Not really, it seems like it just gets ignored.

The content field went to the yaml block, and the body as undefined, like when you leave the field empty

**Comment by ctrl-b** [comment]
@eduardoboucas The same config on dev.staticman.com is working fine,

Just one issue there, when the frontmatter field is not filled out, it generates and undefined content, I think that can be handled by a Jekyll validation.

**Comment by eduardoboucas** [comment]
I really don't get how it's working on the dev instance but not on the live one, since they're both exactly the same at the moment. 😢 

> Just one issue there, when the frontmatter field is not filled out, it generates and undefined content, I think that can be handled by a Jekyll validation.

This sounds like something we should handle in Staticman. I'll look into it.

**Comment by eduardoboucas** [comment]
@usrix If you're still using this, could you please test the live instance again and let me know if the issue persists?

**Comment by SidVal** [comment]
Yes, it persists @eduardoboucas

**Comment by ctrl-b** [comment]
Hello @eduardoboucas It seems like it persists, in my last try the frontmatter field is attached to a YAML var named excerpt

**Comment by SidVal** [comment]
Now it's working !!! :clap:  cc. @eduardoboucas

**Comment by abhin4v** [comment]
I facing the same issue. You can see my staticman.yml file [here](https://github.com/abhin4v/abhin4v.github.io/blob/master/staticman.yml) and an example file generated by staticman in PR [here](https://github.com/abhin4v/abhin4v.github.io/pull/34/files).

**Comment by eduardoboucas** [comment]
I have just re-deployed the live instance and did some testing and it seems to be working fine now. Can you please confirm?

Thanks

**Comment by ctrl-b** [comment]
sorry for the laaaaate reply, but this bug seems hard to squash, the issue just returned (same behaviour as reported on Oct 11 by abhin4v), I want to help, let me know where to start, haven't code for a while, but I can at least check

**Comment by mmistakes** [comment]
Having the same issue.

[**staticman.yml**](https://github.com/mmistakes/gatsby-test/blob/master/staticman.yml)
```yaml
allowedFields: ["name", "email", "url", "message"]
requiredFields: ["name", "email", "message"]

format: "frontmatter"
extension: "md"

transforms:
  message: "frontmatterContent"
```

Transform has no affect, `message` remains in YML front matter, and `undefined` added to the body.

[**Example**](https://github.com/mmistakes/gatsby-test/pull/11/files)
```yaml
---
_id: 975cfb20-6055-11e8-bf3d-35969255318e
_parent: /markup/markup-syntax-highlighting/
name: Foobar Baz
email: ade7352bc2b46f667fb73c91fe19ee9c
url: 'http://foobar.com'
message: This is a comment with some **Markdown**.
date: '2018-05-25T19:55:36.596Z'
timestamp: 1527278136
tags:
  - comment-subscription
type: comment
---
undefined
```
